name: Primer Workflow

on: push # El evento disparador

jobs:
  saludo-job:
    runs-on: ubuntu-latest # El runner (servidor Linux)
    steps:
      - name: Imprimir saludo
        run:  echo "¡Hola! Estoy ejecutando esto automáticamente."

      - name: Listar archivos
        run: ls -la # Comando Linux que ya conoces
